import { useEffect, useMemo, useState } from 'react'
import { IconAlertTriangle, IconCheck, IconChevronDown, IconFileAnalytics, IconRefresh, IconSearch, IconShieldCheck } from '@tabler/icons-react'
import Topbar from '../components/Topbar'
import { supabaseAdmin } from '../lib/supabase'
import { runFinanceAudit } from '../lib/financeAudit'
import './AuditoriaFinanceira.css'

const MONTHS=['','Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro']
const labels={critical:'Inconsistência',warning:'Atenção',review:'Revisar',ok:'Conciliado'}
const monthKeys=data=>[...new Set([...data.dre.map(r=>`${r.ano}-${String(r.mes).padStart(2,'0')}`),...data.managerial.map(r=>`${r.ano}-${String(r.mes).padStart(2,'0')}`),...data.balance.map(r=>r.competencia_date.slice(0,7)),...data.accounts.map(r=>r.competencia_date.slice(0,7))])]

export default function AuditoriaFinanceira(){
  const [data,setData]=useState(null),[loading,setLoading]=useState(true),[selected,setSelected]=useState(''),[filter,setFilter]=useState('open'),[expanded,setExpanded]=useState(new Set())
  async function load(){setLoading(true);const [dre,managerial,balance,accounts,dreAccounts,batches]=await Promise.all([
    supabaseAdmin.from('finance_dre_monthly').select('*').order('ano').order('mes'),supabaseAdmin.from('finance_managerial_monthly').select('*').order('ano').order('mes'),supabaseAdmin.from('finance_balanco').select('*').order('competencia_date'),supabaseAdmin.from('finance_balancete_accounts').select('*'),supabaseAdmin.from('finance_dre_accounts').select('*'),supabaseAdmin.from('finance_import_batches').select('*,finance_import_files(*)')
  ]);const all={dre:dre.data||[],managerial:managerial.data||[],balance:balance.data||[],accounts:accounts.data||[],dreAccounts:dreAccounts.data||[],batches:batches.data||[]};setData(all);const keys=monthKeys(all).sort();setSelected(current=>current||keys.at(-1)||'');setLoading(false)}
  useEffect(()=>{let active=true;Promise.all([
    supabaseAdmin.from('finance_dre_monthly').select('*').order('ano').order('mes'),supabaseAdmin.from('finance_managerial_monthly').select('*').order('ano').order('mes'),supabaseAdmin.from('finance_balanco').select('*').order('competencia_date'),supabaseAdmin.from('finance_balancete_accounts').select('*'),supabaseAdmin.from('finance_dre_accounts').select('*'),supabaseAdmin.from('finance_import_batches').select('*,finance_import_files(*)')
  ]).then(([dre,managerial,balance,accounts,dreAccounts,batches])=>{if(!active)return;const all={dre:dre.data||[],managerial:managerial.data||[],balance:balance.data||[],accounts:accounts.data||[],dreAccounts:dreAccounts.data||[],batches:batches.data||[]};setData(all);const keys=monthKeys(all).sort();setSelected(keys.at(-1)||'');setLoading(false)});return()=>{active=false}},[])
  const months=useMemo(()=>data?monthKeys(data).sort().reverse():[],[data])
  const findings=useMemo(()=>{if(!data||!selected)return[];const [year,month]=selected.split('-').map(Number),competence=`${selected}-01`,prevDate=new Date(year,month-2,1),prevYear=prevDate.getFullYear(),prevMonth=prevDate.getMonth()+1;return runFinanceAudit({year,month,dre:data.dre.find(r=>r.ano===year&&r.mes===month),managerial:data.managerial.find(r=>r.ano===year&&r.mes===month),balance:data.balance.find(r=>r.competencia_date===competence),accounts:data.accounts.filter(r=>r.competencia_date===competence),dreAccounts:data.dreAccounts.filter(r=>r.ano===year&&r.mes===month),previousAccounts:data.accounts.filter(r=>r.competencia_date===`${prevYear}-${String(prevMonth).padStart(2,'0')}-01`),previousManagerial:data.managerial.find(r=>r.ano===prevYear&&r.mes===prevMonth),files:data.batches.filter(r=>r.competencia_date===competence).flatMap(r=>r.finance_import_files||[])})},[data,selected])
  const visible=findings.filter(item=>filter==='all'||(filter==='open'?item.severity!=='ok':item.severity===filter)),counts=Object.fromEntries(['critical','warning','review','ok'].map(key=>[key,findings.filter(f=>f.severity===key).length])),score=findings.length?Math.round(counts.ok/findings.length*100):0
  const toggle=id=>setExpanded(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next})
  if(loading)return <div className="audit-shell"><Topbar title="Auditoria financeira" subtitle="Conciliação automática entre relatórios"/><div className="audit-loading">Cruzando informações financeiras…</div></div>
  return <div className="audit-shell"><Topbar title="Auditoria financeira" subtitle="Conciliação automática entre relatórios"/><main className="audit-page">
    <section className="audit-hero"><div><span>CENTRAL DE CONCILIAÇÃO</span><h1>O que não fecha — e onde procurar.</h1><p>A auditoria cruza DRE, Gerencial, Balanço, Balancete e previsões. Diferenças explicáveis são separadas de inconsistências que exigem correção.</p></div><div className="audit-score"><div style={{'--score':`${score}%`}}><strong>{score}%</strong><small>dos testes conciliados</small></div><select value={selected} onChange={e=>{setSelected(e.target.value);setExpanded(new Set())}}>{months.map(key=>{const[y,m]=key.split('-');return <option key={key} value={key}>{MONTHS[Number(m)]} de {y}</option>})}</select></div></section>
    <section className="audit-summary">{[['critical','Inconsistências'],['warning','Atenções'],['review','Itens para revisar'],['ok','Testes conciliados']].map(([key,label])=><button key={key} className={filter===key?'active':''} onClick={()=>setFilter(filter===key?'all':key)}><i className={key}/><span>{label}</span><strong>{counts[key]}</strong></button>)}</section>
    <section className="audit-toolbar"><div><IconSearch size={17}/><strong>{filter==='open'?'Pendências da competência':filter==='all'?'Todos os testes':labels[filter]}</strong><span>{visible.length} {visible.length===1?'resultado':'resultados'}</span></div><div><button className={filter==='open'?'active':''} onClick={()=>setFilter('open')}>Somente pendências</button><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>Ver tudo</button><button onClick={load}><IconRefresh size={15}/> Atualizar</button></div></section>
    <section className="audit-list">{visible.length?visible.map(item=><article key={item.id} className={`audit-finding ${item.severity}`}><button onClick={()=>toggle(item.id)}><span className="audit-finding-icon">{item.severity==='ok'?<IconCheck size={17}/>:item.severity==='critical'?<IconAlertTriangle size={17}/>:<IconFileAnalytics size={17}/>}</span><div><small>{item.category}</small><h3>{item.title}</h3><p>{item.description}</p></div><b>{labels[item.severity]}</b><IconChevronDown className={expanded.has(item.id)?'open':''} size={18}/></button>{expanded.has(item.id)&&<div className="audit-detail"><div><span>EVIDÊNCIA</span><p>{item.evidence}</p></div><div><span>COMO CONFERIR</span><p>{item.action}</p></div></div>}</article>):<div className="audit-empty"><IconShieldCheck size={30}/><strong>Nenhuma pendência neste filtro.</strong><span>Os testes disponíveis para a competência foram conciliados.</span></div>}</section>
    <footer className="audit-footnote"><IconShieldCheck size={17}/><p><strong>Leitura responsável:</strong> a auditoria aponta diferenças e riscos, mas não altera lançamentos automaticamente. Diferenças entre caixa e competência podem ser legítimas e devem ser confirmadas no ULTRA.</p></footer>
  </main></div>
}
